mv 6.geojson WV.geojson
mv 7.geojson FL.geojson
mv 8.geojson IL.geojson
mv 9.geojson MN.geojson
mv 10.geojson MD.geojson
mv 11.geojson RI.geojson
mv 12.geojson ID.geojson
mv 13.geojson NH.geojson
mv 14.geojson NC.geojson
mv 15.geojson VT.geojson
mv 16.geojson CT.geojson
mv 17.geojson DE.geojson
mv 18.geojson NM.geojson
mv 19.geojson CA.geojson
mv 20.geojson NJ.geojson
mv 21.geojson WI.geojson
mv 22.geojson OR.geojson
mv 23.geojson NE.geojson
mv 24.geojson PA.geojson
mv 25.geojson WA.geojson
mv 26.geojson LA.geojson
mv 27.geojson GA.geojson
mv 28.geojson AL.geojson
mv 29.geojson UT.geojson
mv 30.geojson OH.geojson
mv 31.geojson TX.geojson
mv 32.geojson CO.geojson
mv 33.geojson SC.geojson
mv 34.geojson OK.geojson
mv 35.geojson TN.geojson
mv 36.geojson WY.geojson
mv 37.geojson HI.geojson
mv 38.geojson ND.geojson
mv 39.geojson KY.geojson
mv 40.geojson VI.geojson
mv 41.geojson MP.geojson
mv 42.geojson GU.geojson
mv 43.geojson ME.geojson
mv 44.geojson NY.geojson
mv 45.geojson NV.geojson
mv 46.geojson AK.geojson
mv 47.geojson AS.geojson
mv 48.geojson MI.geojson
mv 49.geojson AR.geojson
mv 50.geojson MS.geojson
mv 51.geojson MO.geojson
mv 52.geojson MT.geojson
mv 53.geojson KS.geojson
mv 54.geojson IN.geojson
mv 55.geojson PR.geojson
mv 56.geojson SD.geojson
mv 57.geojson MA.geojson
mv 58.geojson VA.geojson
mv 59.geojson DC.geojson
mv 60.geojson IA.geojson
mv 61.geojson AZ.geojson
